#define NUM_ANIMATIONS 1
#define SECONDS_PER_DEMO_ANIMATION 10
#define FIXED_ANIMATION true
#define FIXED_ANIMATION_INDEX 0
#define FADE_TO_BLACK_PER_CYCLE_VALUE 4
#define BLUR_ANIMATION false
#define BLUR_VALUE 100