#define USE_COLOR_PALETTES true
#define CHANGE_PALATTE_PERIODICALLY true
#define COLOR_PALETTE_SPEED 45 // speed for switching between palettes
#define COLOR_PALETTE_BLEND_UPDATE_SPEED_MILLISECONDS 10
#define CHANGE_PALETTE_EVERY_N_SECONDS 10
